### PR TITLE
build: Add requirements.txt

### PR DESCRIPTION
**Pull request by abmusse**
Created a virtualenv then pip installed sphinx, recommonmark, and sphinx_rtd_theme. Then generated the `requirements.txt` by running: 

```bash
pip freeze > requirements.txt
```

### CODE REVIEW

**Comment by kadler** [comment]
Technically blocked by #2 and also #1.

**Comment by kadler** [comment]
Please re-open this PR to the master branch

**Comment by abmusse** [comment]
I'm unable to reopen this. The Reopen button is is disabled with the message the `readthedocs branch has been deleted`

**Comment by kadler** [comment]
Sorry, I meant you need to open a new PR since you can't change the branch for a PR once opened.

**Pull request closed without merging**
