### PR TITLE
Split odbc documentation in to separate pages

### PR DESCRIPTION
**Pull request by kadler**
This fixes various issues that Sphinx has with the current docs, since
there are multiple top-level headings in it. It also makes it easier to
read and reference because it's not all in one page and the TOC will be
generated automatically.

### CODE REVIEW

**Comment by kadler** [comment]
FYI @markdirish I noticed in the existing docs, the last sentence in [this section](https://github.com/IBM/ibmi-oss-docs/tree/master/odbc#using-your-dsn) trails off. I was only adjusting formatting so I left it here. Not sure if you know what it was supposed to say.

**Comment by kadler** [comment]
@markdirish can you take a look please?

**Comment by markdirish** [comment]
On it, will push to `split-odbc` branch.

**Comment by markdirish** [comment]
Just deleted, but then realized what I was probably going to talk about: Mixing DSN options with connection string options. Will create another commit.

**Comment by kadler** [comment]
Ok, that looks good to me. Do the other changes look good to you?

**Review by markdirish — APPROVED** [review]
LGTM!

**Pull request merged**
